version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  publisher:
    build: ./Publisher
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
  subscriber:
    build: ./Subscriber
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis